### PR TITLE
Reset request headers after send

### LINKED ISSUE #163: BrowserKit does not allow to reset request header
Using [BrowserKit](https://github.com/Behatch/contexts/blob/master/src/HttpCall/Request/BrowserKit.php), when I execute all scenarios in my feature file, headers are not reset between scenarios.

For example, if I add a `Given I add "CONTENT_TYPE" header equal to "application/json"` step in my first scenario, this header will be kept in the second scenario.

This is a bug as it makes fail my second scenario because of that extra & unwanted header.

### PR DESCRIPTION
**Pull request by vincentchalamon**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #163
| License       | [BEER-WARE](https://github.com/Behatch/contexts/blob/master/LICENSE)

Requires https://github.com/FriendsOfPHP/Goutte/pull/261

### CODE REVIEW

**Comment by vincentchalamon** [comment]
Ping @sanpii

**Comment by MLKiiwy** [comment]
looks good :+1:

**Comment by sanpii** [comment]
Can you add a scenario to prevent regression?

**Comment by vincentchalamon** [comment]
@sanpii OK I'm on it. Do you have an idea how can I test with different Behat configurations? I would like to test with different clients (Goutte vs BrowserKit)

**Comment by sanpii** [comment]
@vincentchalamon you can create a second behat configuration and use `-c` option to load it.

**Comment by samusenkoiv** [comment]
Why can't we create new instance of Sanpi\Behatch\HttpCall\Request each time it is requested  ?

**Comment by vincentchalamon** [comment]
@samusenkoiv You mean in `RestContext`?

**Comment by vincentchalamon** [comment]
@samusenkoiv Originally, `Sanpi\Behatch\HttpCall\Request::getClient` method recreates a request each time it's `Sanpi\Behatch\HttpCall\Request` receive any action (`__call` magic method). But if you request 2 methods on it (e.g. to add 2 headers), the first one will be lost as Request is recreated…

**Comment by webaaz** [comment]
Need this fix!

**Comment by vincentchalamon** [comment]
Still waiting for https://github.com/FriendsOfPHP/Goutte/pull/261

**Comment by vincentchalamon** [comment]
@sanpii Current project requires PHP >=5.4, but [fabpot/goutte](https://github.com/FriendsOfPHP/Goutte/commit/b47916e58d54f8b3abc74bda47f57815720668e4) requires PHP >=5.5. Can I upgrade this dependency in `.travis.yml` & `composer.json` files for production, or should I only force it for testing?

**Comment by webaaz** [comment]
http://php.net/supported-versions.php

**Comment by webaaz** [comment]
There's a 3.2 tag for goutte

**Comment by vincentchalamon** [comment]
Scrutinizer fails to analyze `atoum/atoum` and recommends me to [exclude it from analysis](https://scrutinizer-ci.com/docs/tools/php/php-analyzer/guides/exclude_dependencies). @sanpii @webaaz Maybe there is a better way?

capture d ecran 2016-11-17 a 13 26 34
capture d ecran 2016-11-17 a 13 26 44

**Comment by elkangaroo** [comment]
Is there still anything preventing this fix from getting merged? This would also make PR #157 obsolete (which we currently use in our fork).

**Comment by elkangaroo** [comment]
@vincentchalamon would you mind rebasing your branch against master again? It would be really great to get this PR merged :)

**Comment by vincentchalamon** [comment]
@elkangaroo Fixed

**Comment by elkangaroo** [comment]
@sanpii I see that the only failing test has been failing occasionally on other builds too (and should probably be adjusted, because it makes the build unstable):
```
001 Scenario: Wait before seeing                                # tests/features/browser.feature:63
      Then the total elapsed time should be less than 6 seconds # tests/features/browser.feature:69
```

But other than that, do you think this PR can be merged?

**Comment by vincentchalamon** [comment]
@elkangaroo I'll try to update this PR today to remove deprecated warnings: https://travis-ci.org/Behatch/contexts/jobs/217980052

**Comment by vincentchalamon** [comment]
@elkangaroo @sanpii Deprecated warnings fixed on Travis, I think it was due to forgotten namespaces on https://github.com/Behatch/contexts/commit/86d0b77e31b0f65cecf824e252ccd3cf6abed567.

**Comment by elkangaroo** [comment]
Nice :)
But this 6 seconds test really sucks...
First it failed for PHP 5.5, now 5.5 is green and 5.6 - 7.1 fail. LOL

**Comment by sanpii** [comment]
> But this 6 seconds test really sucks...
It sucks less now: c9ec1849cfff3417f98960d49a69cfff0d2509ba

**Comment by vincentchalamon** [comment]
Ping @sanpii

**Comment by razbakov** [comment]
Any update here? FriendsOfPHP/Goutte#261 is merged.

File: src/HttpCall/Request/Goutte.php [hunk 1]
```diff
@@ -20,25 +20,13 @@ public function send($method, $url, $parameters = [], $files = [], $content = nu
         return $page;
```
Comment (razbakov) [inline src/HttpCall/Request/Goutte.php]:
```
     public function send($method, $url, $parameters = [], $files = [], $content = null, $headers = [])
```

`$headers` are never used here. I propose either to check if `$headers` is not empty and merge array with `$this->requestHeaders` or use `$headers` instead in this case.

It can be useful for tests, where you can set multiple headers in table.

Comment (vincentchalamon) [inline src/HttpCall/Request/Goutte.php]: @razbakov [Fixed](https://github.com/Behatch/contexts/pull/164/files#diff-fe0b1508073cd9ebc25c07b1cd0571f6R17)

**Comment by razbakov** [comment]
@sanpii can you please add a new release tag?
