### PR TITLE
Fix class alias for http call classes

### LINKED ISSUE #200: v2.6 broke our test suite
https://travis-ci.org/api-platform/core/jobs/207362131

### PR DESCRIPTION
**Pull request by sanpii**
Fix #200

### CODE REVIEW

File: src/class_aliases/HttpCall/ContextSuppertedVoter.php [hunk 1]
```diff
@@ -1,5 +1,5 @@
 <?php
 
-@trigger_error('The Sanpi\\Behatch\\ContextSupportedVoter class is deprecated since version 2.3 and will be removed in 3.0. Use the Behatch\\ContextSupportedVoter class instead.', E_USER_DEPRECATED);
+@trigger_error('The Sanpi\\Behatch\\HttpCall\\ContextSupportedVoter class is deprecated since version 2.3 and will be removed in 3.0. Use the Behatch\\HttpCall\\ContextSupportedVoter class instead.', E_USER_DEPRECATED);
```
Comment (teohhanhui) [inline src/class_aliases/HttpCall/ContextSuppertedVoter.php]: @sanpii All these should say "version 2.6", not 2.3

Comment (sanpii) [inline src/class_aliases/HttpCall/ContextSuppertedVoter.php]: You’r right, thank you 😃
